name: 'FRC VendorDep Update Action'
description: 'Updates FRC vendordeps in your repository.'
author: 'garrettsummerfi3ld'

branding:
  icon: 'link'
  color: 'yellow'

inputs:
  dir:
    description: 'The directory to look for the vendordeps.'
    required: false
    default: './vendordeps'
  author:
    description: 'The author of the commit for updating the vendordeps.'
    required: false
    default: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
  token: 
    description: 'The token to use for the commit.'
    required: true
    default: ${{ github.token }}
  dry-run:
    description: 'Whether to run the action in dry-run mode.'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
