name: 'FRC VendorDep Update Action'
description: 'Updates FRC vendordeps in your repository.'
author: 'garrettsummerfi3ld'

branding:
  icon: 'link'
  color: 'yellow'

inputs:
  dir:
    description: 'The directory to look for the vendordeps.'
    required: false
    default: './vendordeps'

runs:
  using: node20
  main: dist/index.js
