name: 'FRC VendorDep Update Action'
description: 'Updates FRC vendordeps in your repository.'
author: 'garrettsummerfi3ld'

branding:
  icon: 'link'
  color: 'yellow'

inputs:
  dir:
    description: 'The directory to look for the vendordeps.'
    required: false
    default: './vendordeps'
  dry-run:
    description: 'Whether to run the action in dry-run mode.'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
